# Generated by Django 6.0.7 on 2026-09-14 09:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USER_FULL_NAME', models.CharField(max_length=200)),
                ('USER_EMAIL', models.EmailField(max_length=254)),
                ('USER_MOBILE_NO', models.CharField(max_length=15)),
                ('USER_ADDRESS', models.TextField()),
                ('USER_IP', models.CharField(max_length=45)),
                ('USER_CREATED_BY', models.CharField(blank=True, max_length=200, null=True)),
                ('USER_MODIFIED_BY', models.CharField(blank=True, max_length=200, null=True)),
                ('USER_CREATED_AT', models.DateTimeField(default=django.utils.timezone.now)),
                ('USER_UPDATED_AT', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'db_table': 'USER PROFILE',
            },
        ),
    ]
