# Generated by Django 6.0.7 on 2026-09-14 10:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EMPLOYEE_FULL_NAME', models.CharField(max_length=200)),
                ('EMPLOYEE_EMAIL', models.EmailField(max_length=254)),
                ('EMPLOYEE_MOBILE_NO', models.CharField(blank=True, max_length=15, null=True)),
                ('EMPLOYEE_ADDRESS', models.TextField()),
                ('EMPLOYEE_IP', models.CharField(blank=True, max_length=45, null=True)),
                ('EMPLOYEE_ROLE', models.CharField(choices=[('ADMIN', 'Admin'), ('CASHIER', 'Cashier'), ('DELIVERY_MAN', 'Delivery Man'), ('MANAGER', 'Manager'), ('STAFF', 'Staff')], default='STAFF', max_length=20)),
                ('EMPLOYEE_PASSWORD', models.CharField(max_length=255)),
                ('EMPLOYEE_CREATED_BY', models.CharField(blank=True, max_length=200, null=True)),
                ('EMPLOYEE_MODIFIED_BY', models.CharField(blank=True, max_length=200, null=True)),
                ('EMPLOYEE_CREATED_AT', models.DateTimeField(default=django.utils.timezone.now)),
                ('EMPLOYEE_UPDATED_AT', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Employee Setup',
                'verbose_name_plural': 'Employee Setups',
                'db_table': 'EMPLOYEE SETUP',
            },
        ),
        migrations.CreateModel(
            name='PublicUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PUBLIC_USER_FULL_NAME', models.CharField(max_length=200)),
                ('PUBLIC_USER_EMAIL', models.EmailField(max_length=254)),
                ('PUBLIC_USER_MOBILE_NO', models.CharField(max_length=15)),
                ('PUBLIC_USER_ADDRESS', models.TextField()),
                ('PUBLIC_USER_IP', models.CharField(max_length=45)),
                ('PUBLIC_USER_PASSWORD', models.CharField(max_length=255)),
                ('PUBLIC_USER_PROFILE_IMAGE', models.ImageField(blank=True, null=True, upload_to='Uploads/Public/Profile_Images/')),
                ('PUBLIC_USER_CREATED_BY', models.CharField(blank=True, max_length=200, null=True)),
                ('PUBLIC_USER_MODIFIED_BY', models.CharField(blank=True, max_length=200, null=True)),
                ('PUBLIC_USER_CREATED_AT', models.DateTimeField(default=django.utils.timezone.now)),
                ('PUBLIC_USER_UPDATED_AT', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Public User Profile',
                'verbose_name_plural': 'Public User Profiles',
                'db_table': 'PUBLIC USER PROFILE',
            },
        ),
    ]
