# Generated by Django 6.0.7 on 2026-09-14 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_alter_gallery_gallery_created_by_and_more'),
        ('users', '0002_employeesetup_publicuserprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
