# Generated by Django 6.1 on 2026-09-17 16:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0014_alter_productrating_options_and_more'),
        ('users', '0003_delete_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_cart_items', to='admin_panel.productsetup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='users.publicuserprofile')),
            ],
            options={
                'verbose_name': 'User Cart Item',
                'verbose_name_plural': 'User Cart Items',
                'db_table': 'USER CART ITEM',
                'unique_together': {('user', 'product')},
            },
        ),
    ]
