# Generated by Django 6.0.7 on 2026-09-14 09:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GALLERY_TITLE', models.CharField(max_length=500)),
                ('GALLERY_IMAGE', models.ImageField(upload_to='Uploads/Gallary/')),
                ('GALLERY_DESCRIPTION', models.TextField()),
                ('GALLERY_CREATED_AT', models.DateTimeField(default=django.utils.timezone.now)),
                ('GALLERY_MODIFIED_AT', models.DateTimeField(auto_now=True)),
                ('GALLERY_CREATED_BY', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='GALLERY_CREATED_BY', to='users.userprofile')),
                ('GALLERY_MODIFIED_BY', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='GALLERY_MODIFIED_BY', to='users.userprofile')),
            ],
            options={
                'db_table': 'GALLERY',
            },
        ),
    ]
