# Generated by Django 6.0.7 on 2026-09-14 09:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NEWS_TYPE', models.CharField(choices=[('GENERAL', 'General'), ('ANNOUNCEMENT', 'Announcement'), ('EVENT', 'Event'), ('UPDATE', 'Update'), ('NOTICE', 'Notice'), ('BLOG', 'Blog'), ('PRESS_RELEASE', 'Press Release')], max_length=50)),
                ('NEWS_TITLE', models.CharField(max_length=500)),
                ('NEWS_IMAGE', models.ImageField(upload_to='Uploads/News/')),
                ('NEWS_DESCRIPTION', models.TextField()),
                ('NEWS_CREATED_AT', models.DateTimeField(default=django.utils.timezone.now)),
                ('NEWS_MODIFIED_AT', models.DateTimeField(auto_now=True)),
                ('NEWS_CREATED_BY', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='NEWS_CREATED_BY', to='users.userprofile')),
                ('NEWS_MODIFIED_BY', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='NEWS_MODIFIED_BY', to='users.userprofile')),
            ],
            options={
                'db_table': 'NEWS',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CATEGORY_NAME', models.CharField(max_length=200)),
                ('CATEGORY_CREATED_AT', models.DateTimeField(default=django.utils.timezone.now)),
                ('CATEGORY_MODIFIED_AT', models.DateTimeField(auto_now=True)),
                ('CATEGORY_CREATED_BY', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='CATEGORY_CREATED_BY', to='users.userprofile')),
                ('CATEGORY_MODIFIED_BY', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='CATEGORY_MODIFIED_BY', to='users.userprofile')),
            ],
            options={
                'db_table': 'PRODUCT CATEGORY',
            },
        ),
        migrations.CreateModel(
            name='ProductSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PRODUCT_NAME', models.CharField(max_length=300)),
                ('PRODUCT_PRICE', models.DecimalField(decimal_places=2, max_digits=15)),
                ('PRODUCT_RATING', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('PRODUCT_DESCRIPTION', models.TextField()),
                ('PRODUCT_IMAGE', models.ImageField(upload_to='Uploads/Product Images/')),
                ('PRODUCT_CREATED_AT', models.DateTimeField(default=django.utils.timezone.now)),
                ('PRODUCT_MODIFIED_AT', models.DateTimeField(auto_now=True)),
                ('PRODUCT_CATEGORY', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='PRODUCT_CATEGORY', to='admin_panel.productcategory')),
                ('PRODUCT_CREATED_BY', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='PRODUCT_CREATED_BY', to='users.userprofile')),
                ('PRODUCT_MODIFIED_BY', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='PRODUCT_MODIFIED_BY', to='users.userprofile')),
            ],
            options={
                'db_table': 'PRODUCT SETUP',
            },
        ),
        migrations.CreateModel(
            name='ProductOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PRODUCT_ORDER_ID', models.CharField(editable=False, max_length=30, unique=True)),
                ('PRODUCT_ORDER_QTY', models.DecimalField(decimal_places=2, max_digits=15)),
                ('PRODUCT_ORDER_STATUS', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('PROCESSING', 'Processing'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=30)),
                ('PRODUCT_ORDER_CREATED_AT', models.DateTimeField(default=django.utils.timezone.now)),
                ('PRODUCT_ORDER_MODIFIED_AT', models.DateTimeField(auto_now=True)),
                ('PRODUCT_ORDER_CREATED_BY', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='PRODUCT_ORDER_CREATED_BY', to='users.userprofile')),
                ('PRODUCT_ORDER_MODIFIED_BY', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='PRODUCT_ORDER_MODIFIED_BY', to='users.userprofile')),
                ('PRODUCT_ORDER_USER', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='PRODUCT_ORDERS', to='users.userprofile')),
                ('PRODUCT_ORDER_PRODUCT', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='PRODUCT_ORDERS', to='admin_panel.productsetup')),
            ],
            options={
                'db_table': 'PRODUCT ORDER',
            },
        ),
        migrations.CreateModel(
            name='UnitSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UNIT_NAME', models.CharField(max_length=200)),
                ('UNIT_SYMBOL', models.CharField(max_length=50)),
                ('UNIT_CREATED_AT', models.DateTimeField(default=django.utils.timezone.now)),
                ('UNIT_MODIFIED_AT', models.DateTimeField(auto_now=True)),
                ('UNIT_CREATED_BY', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='UNIT_CREATED_BY', to='users.userprofile')),
                ('UNIT_MODIFIED_BY', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='UNIT_MODIFIED_BY', to='users.userprofile')),
            ],
            options={
                'db_table': 'UNIT SETUP',
            },
        ),
        migrations.AddField(
            model_name='productsetup',
            name='PRODUCT_UNIT',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='PRODUCT_UNIT', to='admin_panel.unitsetup'),
        ),
    ]
