# Generated by Django 6.0.7 on 2026-09-14 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_news_productcategory_productsetup_productorder_and_more'),
        ('users', '0002_employeesetup_publicuserprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='GALLERY_CREATED_BY',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='GALLERY_CREATED_BY', to='users.employeesetup'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='GALLERY_MODIFIED_BY',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='GALLERY_MODIFIED_BY', to='users.employeesetup'),
        ),
        migrations.AlterField(
            model_name='news',
            name='NEWS_CREATED_BY',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='NEWS_CREATED_BY', to='users.employeesetup'),
        ),
        migrations.AlterField(
            model_name='news',
            name='NEWS_MODIFIED_BY',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='NEWS_MODIFIED_BY', to='users.employeesetup'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='CATEGORY_CREATED_BY',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='CATEGORY_CREATED_BY', to='users.employeesetup'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='CATEGORY_MODIFIED_BY',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='CATEGORY_MODIFIED_BY', to='users.employeesetup'),
        ),
        migrations.AlterField(
            model_name='productorder',
            name='PRODUCT_ORDER_CREATED_BY',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='PRODUCT_ORDER_CREATED_BY', to='users.employeesetup'),
        ),
        migrations.AlterField(
            model_name='productorder',
            name='PRODUCT_ORDER_MODIFIED_BY',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='PRODUCT_ORDER_MODIFIED_BY', to='users.employeesetup'),
        ),
        migrations.AlterField(
            model_name='productorder',
            name='PRODUCT_ORDER_USER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='PRODUCT_ORDERS', to='users.employeesetup'),
        ),
        migrations.AlterField(
            model_name='productsetup',
            name='PRODUCT_CREATED_BY',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='PRODUCT_CREATED_BY', to='users.employeesetup'),
        ),
        migrations.AlterField(
            model_name='productsetup',
            name='PRODUCT_MODIFIED_BY',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='PRODUCT_MODIFIED_BY', to='users.employeesetup'),
        ),
        migrations.AlterField(
            model_name='unitsetup',
            name='UNIT_CREATED_BY',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='UNIT_CREATED_BY', to='users.employeesetup'),
        ),
        migrations.AlterField(
            model_name='unitsetup',
            name='UNIT_MODIFIED_BY',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='UNIT_MODIFIED_BY', to='users.employeesetup'),
        ),
    ]
