# Generated by Django 6.0.7 on 2026-09-14 10:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_alter_gallery_gallery_created_by_and_more'),
        ('users', '0003_delete_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsetup',
            name='PRODUCT_RATING',
        ),
        migrations.CreateModel(
            name='ProductRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PRODUCT_RATING_VALUE', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('PRODUCT_RATING_COMMENT', models.TextField(blank=True, null=True)),
                ('PRODUCT_RATING_CREATED_AT', models.DateTimeField(default=django.utils.timezone.now)),
                ('PRODUCT_RATING_MODIFIED_AT', models.DateTimeField(auto_now=True)),
                ('PRODUCT_RATING_PRODUCT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PRODUCT_RATINGS', to='admin_panel.productsetup')),
                ('PRODUCT_RATING_USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PRODUCT_RATINGS', to='users.publicuserprofile')),
            ],
            options={
                'db_table': 'PRODUCT RATING',
            },
        ),
    ]
