# Generated by Django 6.0.7 on 2026-09-14 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_remove_productsetup_product_rating_productrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='GALLERY_SLUG',
            field=models.SlugField(blank=True, max_length=500, unique=True),
        ),
        migrations.AddField(
            model_name='news',
            name='NEWS_SLUG',
            field=models.SlugField(blank=True, max_length=500, unique=True),
        ),
    ]
