# Generated by Django 6.1 on 2026-09-15 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0005_gallery_gallery_slug_news_news_slug'),
        ('users', '0003_delete_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='NEWS_CREATED_BY',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='NEWS_CREATED_BY', to='users.employeesetup'),
        ),
        migrations.AlterField(
            model_name='news',
            name='NEWS_IMAGE',
            field=models.ImageField(blank=True, null=True, upload_to='Uploads/News/'),
        ),
        migrations.AlterField(
            model_name='news',
            name='NEWS_MODIFIED_BY',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='NEWS_MODIFIED_BY', to='users.employeesetup'),
        ),
        migrations.AlterField(
            model_name='news',
            name='NEWS_TYPE',
            field=models.CharField(choices=[('ANNOUNCEMENT', 'Announcement'), ('CERTIFICATION', 'Certification'), ('UPDATE', 'Update'), ('EVENT', 'Event'), ('PRESS', 'Press'), ('NOTICE', 'Notice'), ('GENERAL', 'General')], default='ANNOUNCEMENT', max_length=50),
        ),
    ]
