# Generated by Django 6.0.7 on 2026-09-15 07:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0005_gallery_gallery_slug_news_news_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsetup',
            name='PRODUCT_IMAGE',
            field=models.ImageField(blank=True, null=True, upload_to='Uploads/Product Images/'),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IMAGE', models.ImageField(upload_to='Uploads/Product Images/')),
                ('CREATED_AT', models.DateTimeField(default=django.utils.timezone.now)),
                ('PRODUCT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PRODUCT_IMAGES', to='admin_panel.productsetup')),
            ],
            options={
                'db_table': 'PRODUCT IMAGE',
            },
        ),
    ]
