# Generated by Django 6.1 on 2026-09-15 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0006_alter_news_news_created_by_alter_news_news_image_and_more'),
        ('users', '0003_delete_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='CATEGORY_CREATED_BY',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='CATEGORY_CREATED_BY', to='users.employeesetup'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='CATEGORY_MODIFIED_BY',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='CATEGORY_MODIFIED_BY', to='users.employeesetup'),
        ),
        migrations.AlterField(
            model_name='productsetup',
            name='PRODUCT_CREATED_BY',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='PRODUCT_CREATED_BY', to='users.employeesetup'),
        ),
        migrations.AlterField(
            model_name='productsetup',
            name='PRODUCT_MODIFIED_BY',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='PRODUCT_MODIFIED_BY', to='users.employeesetup'),
        ),
        migrations.AlterField(
            model_name='unitsetup',
            name='UNIT_CREATED_BY',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='UNIT_CREATED_BY', to='users.employeesetup'),
        ),
        migrations.AlterField(
            model_name='unitsetup',
            name='UNIT_MODIFIED_BY',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='UNIT_MODIFIED_BY', to='users.employeesetup'),
        ),
    ]
