# Generated by Django 6.0.7 on 2026-09-15 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0006_alter_productsetup_product_image_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsetup',
            name='PRODUCT_KEY_FEATURES',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productsetup',
            name='PRODUCT_SIZE',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='productsetup',
            name='PRODUCT_WEIGHT',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
