# Generated by Django 6.0.7 on 2026-09-15 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0007_productsetup_product_key_features_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='CATEGORY_IMAGE',
            field=models.ImageField(blank=True, null=True, upload_to='Uploads/Category Images/'),
        ),
    ]
