# Generated by Django 6.0.7 on 2026-09-15 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0008_productcategory_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsetup',
            name='PRODUCT_SLUG',
            field=models.SlugField(blank=True, max_length=500, unique=True),
        ),
    ]
