# Generated by Django 6.1 on 2026-09-16 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0007_alter_productcategory_category_created_by_and_more'),
        ('admin_panel', '0009_productsetup_product_slug'),
    ]

    operations = [
    ]
