# Generated by Django 6.1.1 on 2026-09-17 04:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0009_productsetup_product_slug'),
        ('users', '0003_delete_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='NEWS_CREATED_BY',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='NEWS_CREATED_BY', to='users.employeesetup'),
        ),
        migrations.AlterField(
            model_name='news',
            name='NEWS_IMAGE',
            field=models.ImageField(blank=True, null=True, upload_to='Uploads/News/'),
        ),
        migrations.AlterField(
            model_name='news',
            name='NEWS_MODIFIED_BY',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='NEWS_MODIFIED_BY', to='users.employeesetup'),
        ),
        migrations.CreateModel(
            name='NewsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IMAGE', models.ImageField(upload_to='Uploads/News/')),
                ('CREATED_AT', models.DateTimeField(default=django.utils.timezone.now)),
                ('NEWS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='NEWS_IMAGES', to='admin_panel.news')),
            ],
            options={
                'db_table': 'NEWS IMAGE',
            },
        ),
    ]
