# Generated by Django 6.1.1 on 2026-09-17 04:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0010_alter_news_news_created_by_alter_news_news_image_and_more'),
        ('users', '0003_delete_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='GALLERY_CREATED_BY',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='GALLERY_CREATED_BY', to='users.employeesetup'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='GALLERY_IMAGE',
            field=models.ImageField(blank=True, null=True, upload_to='Uploads/Gallary/'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='GALLERY_MODIFIED_BY',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='GALLERY_MODIFIED_BY', to='users.employeesetup'),
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IMAGE', models.ImageField(upload_to='Uploads/Gallary/')),
                ('CREATED_AT', models.DateTimeField(default=django.utils.timezone.now)),
                ('GALLERY', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='GALLERY_IMAGES', to='admin_panel.gallery')),
            ],
            options={
                'db_table': 'GALLERY IMAGE',
            },
        ),
    ]
