# Generated by Django 6.1 on 2026-09-17 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0010_merge_20260916_1058'),
        ('admin_panel', '0011_alter_gallery_gallery_created_by_and_more'),
    ]

    operations = [
    ]
