# Generated by Django 6.1 on 2026-09-17 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0012_merge_20260917_1357'),
        ('users', '0003_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='CATEGORY_TAG',
            field=models.CharField(blank=True, help_text="Highlight badge/tag (e.g. 'HEALTH & IMMUNITY', 'TEAS & INFUSIONS')", max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='NEWS_CREATED_BY',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='NEWS_CREATED_BY', to='users.employeesetup'),
        ),
        migrations.AlterField(
            model_name='news',
            name='NEWS_MODIFIED_BY',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='NEWS_MODIFIED_BY', to='users.employeesetup'),
        ),
    ]
