# Generated by Django 6.1 on 2026-09-17 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0013_productcategory_category_tag_and_more'),
        ('users', '0003_delete_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productrating',
            options={'ordering': ['-IS_FEATURED', '-PRODUCT_RATING_CREATED_AT']},
        ),
        migrations.AddField(
            model_name='productrating',
            name='COMMENT_ENG',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productrating',
            name='COMMENT_NEP',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productrating',
            name='IS_FEATURED',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productrating',
            name='IS_VERIFIED',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productrating',
            name='REVIEWER_LOCATION',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='productrating',
            name='REVIEWER_NAME',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='productrating',
            name='PRODUCT_RATING_USER',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='PRODUCT_RATINGS', to='users.publicuserprofile'),
        ),
        migrations.AlterField(
            model_name='productrating',
            name='PRODUCT_RATING_VALUE',
            field=models.DecimalField(decimal_places=1, default=5.0, max_digits=2),
        ),
    ]
