# Generated by Django 6.1 on 2026-09-18 06:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0014_alter_productrating_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HERO_BANNER_IMAGE', models.ImageField(blank=True, null=True, upload_to='Uploads/Hospital/')),
                ('HERO_TITLE_ENG', models.CharField(blank=True, default='Holistic Hospital & Research Center', max_length=255)),
                ('HERO_TITLE_NEP', models.CharField(blank=True, default='होलिस्टिक हस्पिटल एण्ड रिसर्च सेन्टर', max_length=255)),
                ('HERO_SUBTITLE_ENG', models.CharField(blank=True, default='Integrated Natural Healthcare & Rehabilitation', max_length=500)),
                ('HERO_SUBTITLE_NEP', models.CharField(blank=True, default='प्राकृतिक चिकित्सा र पुनस्र्थापना सेवा', max_length=500)),
                ('INTRO_TITLE_ENG', models.CharField(blank=True, default='Introduction', max_length=255)),
                ('INTRO_TITLE_NEP', models.CharField(blank=True, default='परिचय', max_length=255)),
                ('INTRO_TEXT_NEP', models.TextField(help_text='Nepali intro paragraph from legacy website')),
                ('INTRO_TEXT_ENG', models.TextField(blank=True, default='', help_text='English intro paragraph (falls back to Nepali)')),
                ('DISEASES_TITLE_ENG', models.CharField(blank=True, default='Conditions & Diseases Treated', max_length=255)),
                ('DISEASES_TITLE_NEP', models.CharField(blank=True, default='उपचार गरिने रोग तथा समस्याहरू', max_length=255)),
                ('DISEASES_TEXT_NEP', models.TextField(help_text='Nepali disease list / descriptions from legacy website')),
                ('DISEASES_TEXT_ENG', models.TextField(blank=True, default='', help_text='English disease list (falls back to Nepali)')),
                ('PARALYSIS_TITLE_ENG', models.CharField(blank=True, default='Comprehensive Paralysis Rehabilitation', max_length=255)),
                ('PARALYSIS_TITLE_NEP', models.CharField(blank=True, default='प्यारालाइसिस (पक्षघात) को सफल प्राकृतिक उपचार', max_length=255)),
                ('PARALYSIS_DESC_NEP', models.TextField(blank=True, default='')),
                ('PARALYSIS_DESC_ENG', models.TextField(blank=True, default='')),
                ('PARALYSIS_BANNER_IMAGE', models.ImageField(blank=True, null=True, upload_to='Uploads/Hospital/')),
                ('CONTACT_PHONE', models.CharField(blank=True, default='+977-1-4795586, 9851088497', max_length=100)),
                ('CONTACT_EMAIL', models.EmailField(blank=True, default='info@holisticnepal.com', max_length=254)),
                ('CONTACT_LOCATION_ENG', models.CharField(blank=True, default='Balkhu, Kathmandu, Nepal', max_length=255)),
                ('CONTACT_LOCATION_NEP', models.CharField(blank=True, default='बल्खु, काठमाडौं, नेपाल', max_length=255)),
                ('IS_ACTIVE', models.BooleanField(default=True)),
                ('UPDATED_AT', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hospital Information',
                'verbose_name_plural': 'Hospital Information',
                'db_table': 'HOSPITAL_INFO',
            },
        ),
        migrations.CreateModel(
            name='HospitalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SERVICE_NAME_NEP', models.CharField(max_length=255)),
                ('SERVICE_NAME_ENG', models.CharField(blank=True, default='', max_length=255)),
                ('SERVICE_IMAGE', models.ImageField(blank=True, null=True, upload_to='Uploads/Hospital/Services/')),
                ('SERVICE_ORDER', models.PositiveIntegerField(default=1)),
                ('IS_ACTIVE', models.BooleanField(default=True)),
                ('CREATED_AT', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Hospital Service',
                'verbose_name_plural': 'Hospital Services',
                'db_table': 'HOSPITAL_SERVICE',
                'ordering': ['SERVICE_ORDER', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HospitalServiceTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TAG_LABEL_NEP', models.CharField(max_length=255)),
                ('TAG_LABEL_ENG', models.CharField(blank=True, default='', max_length=255)),
                ('TAG_ORDER', models.PositiveIntegerField(default=1)),
                ('IS_ACTIVE', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Hospital Service Tag / Therapy',
                'verbose_name_plural': 'Hospital Service Tags / Therapies',
                'db_table': 'HOSPITAL_SERVICE_TAG',
                'ordering': ['TAG_ORDER', 'id'],
            },
        ),
    ]
