# Generated by Django 6.1 on 2026-09-19 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0015_hospitalinfo_hospitalservice_hospitalservicetag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalinfo',
            name='CONTACT_LOCATION_ENG',
            field=models.CharField(blank=True, default='Thulo Kharibot Marga, Kathmandu, Bagmati Province 44600', max_length=255),
        ),
        migrations.AlterField(
            model_name='hospitalinfo',
            name='CONTACT_LOCATION_NEP',
            field=models.CharField(blank=True, default='ठूलो खरीबोट मार्ग, काठमाडौं, बागमती प्रदेश ४४६००', max_length=255),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='URL slug e.g. hydrotherapy', max_length=100, unique=True)),
                ('name_en', models.CharField(max_length=255)),
                ('name_np', models.CharField(max_length=255)),
                ('summary_en', models.CharField(help_text='One-line description in English', max_length=500)),
                ('summary_np', models.CharField(help_text='One-line description in Nepali', max_length=500)),
                ('hero_description_en', models.TextField(help_text='Full one-paragraph introduction in English')),
                ('hero_description_np', models.TextField(help_text='Full one-paragraph introduction in Nepali')),
                ('conditions_treated_en', models.JSONField(blank=True, default=list, help_text='List of strings in English')),
                ('conditions_treated_np', models.JSONField(blank=True, default=list, help_text='List of strings in Nepali')),
                ('how_it_works', models.JSONField(blank=True, default=list, help_text="List of step objects: [{'title_en': ..., 'title_np': ..., 'desc_en': ..., 'desc_np': ...}]")),
                ('duration', models.CharField(blank=True, default='45 Mins', max_length=100)),
                ('physiological_action_en', models.CharField(blank=True, default='', max_length=255)),
                ('physiological_action_np', models.CharField(blank=True, default='', max_length=255)),
                ('primary_indication_en', models.CharField(blank=True, default='', max_length=255)),
                ('primary_indication_np', models.CharField(blank=True, default='', max_length=255)),
                ('icon', models.CharField(blank=True, default='leaf', help_text='Icon identifier e.g. droplet, leaf, hands', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('related_services', models.ManyToManyField(blank=True, related_name='linked_from', to='admin_panel.service')),
            ],
            options={
                'verbose_name': 'Clinical Service Page',
                'verbose_name_plural': 'Clinical Service Pages',
                'db_table': 'HOSPITAL_SERVICE_PAGE',
                'ordering': ['order', 'id'],
            },
        ),
    ]
