# Generated by Django 6.1 on 2026-09-19 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0016_alter_hospitalinfo_contact_location_eng_and_more'),
        ('users', '0004_usercartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorder',
            name='CUSTOMER',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='CUSTOMER_ORDERS', to='users.publicuserprofile'),
        ),
        migrations.AddField(
            model_name='productorder',
            name='DELIVERY_INSTRUCTIONS',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='productorder',
            name='IS_PAID',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productorder',
            name='ORDER_ITEMS_DATA',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='productorder',
            name='ORDER_SOURCE',
            field=models.CharField(choices=[('WEB', 'Customer Web Order'), ('INTERNAL', 'Internal Order')], default='WEB', max_length=20),
        ),
        migrations.AddField(
            model_name='productorder',
            name='PAYMENT_METHOD',
            field=models.CharField(blank=True, default='COD', max_length=50),
        ),
        migrations.AddField(
            model_name='productorder',
            name='SHIPPING_ADDRESS',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='productorder',
            name='SHIPPING_EMAIL',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='productorder',
            name='SHIPPING_FEE',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='productorder',
            name='SHIPPING_NAME',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='productorder',
            name='SHIPPING_PHONE',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='productorder',
            name='TOTAL_AMOUNT',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='hospitalinfo',
            name='CONTACT_PHONE',
            field=models.CharField(blank=True, default='01-4115830, 9851088497', max_length=100),
        ),
        migrations.AlterField(
            model_name='productorder',
            name='PRODUCT_ORDER_CREATED_BY',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='PRODUCT_ORDER_CREATED_BY', to='users.employeesetup'),
        ),
        migrations.AlterField(
            model_name='productorder',
            name='PRODUCT_ORDER_MODIFIED_BY',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='PRODUCT_ORDER_MODIFIED_BY', to='users.employeesetup'),
        ),
        migrations.AlterField(
            model_name='productorder',
            name='PRODUCT_ORDER_PRODUCT',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='PRODUCT_ORDERS', to='admin_panel.productsetup'),
        ),
        migrations.AlterField(
            model_name='productorder',
            name='PRODUCT_ORDER_QTY',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='productorder',
            name='PRODUCT_ORDER_USER',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='PRODUCT_ORDERS', to='users.employeesetup'),
        ),
    ]
